### ISSUE TITLE
Can't link to notes for August 28th and 30th

### ISSUE THREAD

**Issue by MadieMunro** [msu/csci-432-fall2023#1]
**Describe the bug**
Under the "Schedule" tab for the main CSCI 432 page, when I try to click on the notes for August 28th and 30th, I get a 404 error.

**To Reproduce**
1. Go to https://msu.github.io/csci-432-fall2023/
2. Click on "Schedule"
3. Scroll down to August 28th or 30th, click on either "Induction" or "Asymptotic Notation"
4. A 404 Error page should pop up

**Expected behavior**
It is expected that when I click on either one of those links, the notes going over those concepts should appear, not an error page.

**Screenshots**
![image](https://github.com/msu/csci-432-fall2023/assets/89541799/1e7640eb-9b92-454e-b4e3-55c775bb3a95)
![image](https://github.com/msu/csci-432-fall2023/assets/89541799/05cda23f-2adb-432b-9b97-6e954bf8906f)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Browser: Google Chrome
 - Version: 116.0.5845.111
 
**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.6
 - Browser: Google Chrome
 - Version: 116.0.5845.146

**Additional context**
I couldn't even navigate to "Schedule" on my phone (the icon for the pop-up menu doesn't appear to be functional).

**Comment by brittany** [comment]
@LiamFallon213 - please address this PR and see the email I sent you with more details.

@MadieMunro - thanks for the issue request.  The 8/28 notes were fixed, and the 8/30 notes are currently jpgs in the wrong location (in the root of the repo).  If you want practice with a PR, you can issue a PR to fix it!  I'll send you an email with more details.

**Comment by LiamFallon213** [comment]
I have fixed the 8/30 notes
